### ISSUE TITLE
[BUG] Simillar SkillUniqueID in diferent addons

### ISSUE THREAD

**Issue by Luerl21** [K4ryuu/K4-RPG#1]
https://github.com/K4ryuu/K4-RPG-Health/blob/5c28065dcf730de8fcd331707324a951246dd07b/src/K4-RPG-Health.cs#L45
https://github.com/K4ryuu/K4-RPG-KnifeCrits/blob/dd4d82dca11c7a90a33e2f1e580e93a7451b7a1c/src/K4-RPG-KnifeCrits.cs#L45
https://github.com/K4ryuu/K4-RPG-Speed/blob/df7c3b1986a8f0cc9d0228f80fc3d19434694fd3/src/K4-RPG-Speed.cs#L45

**Comment by K4ryuu** [comment]
You are absolutely right. This was a mistake of copy pasting the template skill. :(
I update all skill repos today with the proper names and some other config values such as min level and is vip.

**Comment by K4ryuu** [comment]
I have patched all the skills. Fixed the name, id, description problems and additionally added IsVIP and MinLevel to all skill configs.
