### ISSUE TITLE
[BUG] Unable to save player data to database

### ISSUE THREAD

**Issue by Oz-Lin** [K4ryuu/K4-RPG#5]
As in the Discord forum https://discordapp.com/channels/1160907911501991946/1237016262618517566/1256540236570165321

I encountered a bug where player data wasn't stored in the database correctly.

I made a separate database with MariaDB 10.7 utf8mb4_unicode_ci schema. Two tables `k4-rpg_players` and `k4-rpg_playerskills` created, but no player data.

Both tables are blank. Player data gone after changing maps.
Currently on latest metamod and css api v246. Running server on Ubuntu 22.04

**Comment by K4ryuu** [comment]
There was an issue with that and got fixed with this commit: https://github.com/K4ryuu/K4-RPG/commit/0e96d3287ee28925617a7d065579a5bcadf0125c
Are you sure you are using the updated version that is after this commit?

**Comment by Oz-Lin** [comment]
I use the latest release v1.0.2

Will let you know after testing the latest release

**Comment by Oz-Lin** [comment]
Still no player data after compiling commit https://github.com/K4ryuu/K4-RPG/commit/0e96d3287ee28925617a7d065579a5bcadf0125c from scratch

![图片](https://github.com/K4ryuu/K4-RPG/assets/36224575/4c53c4a1-aeb2-476a-9de8-363c014c9ba8)
